apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: tutorial
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/user05-gateway:latest
          ports:
            - containerPort: 8080
